function MakepOptions()
	if pOptions then
		pOptions:SetVisible(true)
		pOptions:MakePopup()
		return
	end

	local Window = vgui.Create("DFrame")
	local truewide = 800
	local truetall = 700
	Window:SetSize(truewide, truetall)
	local wide = (w - truewide) * 0.5
	local tall = (h - truetall) * 0.5
	Window:SetPos(wide, tall)
	Window:SetTitle(" ")
	Window:SetVisible(true)
	Window:SetDraggable(false)
	Window:SetKeyboardInputEnabled(false)
	Window:MakePopup()
	Window:SetDeleteOnClose(false)
	Window:SetCursor("pointer")
	pOptions = Window

	surface.SetFont("teamplay")
	local texw, texh = surface.GetTextSize("Options")
	local label = vgui.Create("DLabel", Window)
	label:SetSize(texw, texh)
	label:SetTextColor(COLOR_RED)
	label:SetFont("teamplay")
	label:SetText("Options")
	label:SetPos(truewide * 0.5 - texw * 0.5, 2)
	label:SetMouseInputEnabled(false)
	surface.SetFont("teamplay")
	local texw, texh = surface.GetTextSize("F1: Help")
	label:SetSize(texw, texh)

	surface.SetFont("Default")
	local ___, defh = surface.GetTextSize("|")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(64, 50)
	slider:SetSize(320, 48)
	slider:SetDecimals(2)
	slider:SetMinMax(0.01, 2)
	slider:SetConVar("teamplay_crosshairscale")
	slider:SetText("Crosshair size")

	--[[local check = vgui.Create("DCheckBoxLabel", Window)
	check:SetPos(64, 100)
	check:SetSize(wide, 32)
	check:SetText("Enable EP2 Motion Blur")
	check:SetConVar("mat_motion_blur_enabled")]]

	local check = vgui.Create("DCheckBoxLabel", Window)
	check:SetPos(64, 130)
	check:SetSize(wide, 32)
	check:SetText("Don't go through friendly teleports")
	check:SetConVar("nox_declinefriendlyteleports")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(64, 190)
	slider:SetSize(320, 48)
	slider:SetDecimals(0)
	slider:SetMinMax(0, 1600)
	slider:SetConVar("cl_detaildist")
	slider:SetText("Grass draw distance")

	--[[local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(64, 340)
	slider:SetSize(200, 48)
	slider:SetDecimals(2)
	slider:SetMinMax(0, 1.5)
	slider:SetConVar("nox_dodgetime")
	slider:SetText("Dodging double tap time (0 disables dodging)")]]

	local check = vgui.Create("DCheckBoxLabel", Window)
	check:SetPos(64, 390)
	check:SetSize(wide, 32)
	check:SetText("Use large spell icons")
	check:SetConVar("nox_hud_largespellicons")
	
	local check = vgui.Create("DCheckBoxLabel", Window)
	check:SetPos(64, 450)
	check:SetSize(wide, 32)
	check:SetText("Use old mana/health display")
	check:SetConVar("nox_hud_oldstyle")
	
	local check = vgui.Create("DCheckBoxLabel", Window)
	check:SetPos(64, 510)
	check:SetSize(wide, 32)
	check:SetText("Toggle screen tilt")
	check:SetConVar("tp_view_headtilt")
	local x = truewide * 0.6

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 50)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_health_x")
	slider:SetText("Health X-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 100)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_health_y")
	slider:SetText("Health Y-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 150)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_mana_x")
	slider:SetText("Mana X-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 200)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_mana_y")
	slider:SetText("Mana Y-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 250)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_bowcharge_x")
	slider:SetText("Longbow Power X-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 300)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_bowcharge_y")
	slider:SetText("Longbow Power Y-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 350)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_statusbar_x")
	slider:SetText("Status Bar X-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 400)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_statusbar_y")
	slider:SetText("Status Bar Y-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 450)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_spellmenu_x")
	slider:SetText("Spell Menu X-position")

	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 500)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_spellmenu_y")
	slider:SetText("Spell Menu Y-position")
	
	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 550)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_nbar_x")
	slider:SetText("Multi-Bar X-position")
	
	local slider = vgui.Create("DNumSlider", Window)
	slider:SetPos(x, 600)
	slider:SetSize(320, 48)
	slider:SetDecimals(3)
	slider:SetMinMax(0, 0.999)
	slider:SetConVar("nox_hud_nbar_y")
	slider:SetText("Multi-Bar Y-position")

	local button = vgui.Create("DButton", Window)
	button:SetText("Restore HUD Defaults")
	button:SizeToContents()
	button:SetWide(button:GetWide() + 16)
	button:SetTall(button:GetTall() + 8)
	button:SetPos(x, 650)
	button.DoClick = function(db)
		GAMEMODE:RestoreHUDDefaults()
	end

	local button = vgui.Create("DButton", Window)
	button:SetPos(truewide * 0.5 - 50, Window:GetTall() - 32)
	button:SetSize(100, 28)
	button:SetText("Close")
	button.DoClick = function(btn) btn:GetParent():SetVisible(false) end
end
