GM.GameTypes = {"CTF", "HTF", "ASLT", "KOTH"} --, "HVST", "ASLT", "BLTZ" }
GM.GameTypeDescriptions = {
	--ASLT = "Destroy the enemy core while protecting your own!",
	--BLTZ = "One ball exists on the map. Bring it to the enemy goal to score!",
	--HVST = "Be the first team to fill your grand capacitor with mana!",
	CTF = "Steal the enemy flag and bring it back to your base while defending your own!",
	HTF = "Hold the neutral flag for as long as possible!",
	ASLT = "Destroy the enemy core while protecting your own!",
	KOTH = "Control the alternating hill area the longest!"
}
GM.GameTranslates = {
	--ASLT = "Assault",
	--BLTZ = "Blitz",
	--HVST = "Harvest",
	CTF = "Capture the Flag",
	HTF = "Hold the Flag",
	ASLT = "Assault",
	KOTH = "King of the Hill"
}

DIRECTORY = "noxctfspellsheet"

PROPTYPES = {}
--SPELLS = {}
spells = {}
--[[Spells = {}
NameToSpell = {}
NameToSpellLower = {}
SpellFunctions = {}]]
CLASSES = {}
TEAMS_PLAYING = {}

BUILD_DISTANCE_TO_ENEMY = 1024

GAMESTATE_BUILD = 0
GAMESTATE_BUILDMODE = GAMESTATE_BUILD
GAMESTATE_VERIFY = 1
GAMESTATE_PLAY = 2

GROUP_MAGIC = "Magic"
GROUP_HYBRID = "Hybrid"
GROUP_MELEE = "Melee"
GROUP_OTHER = GROUP_MELEE

MANA_SLOWEST = 1
MANA_SLOWER = 2
MANA_SLOW = 3
MANA_NORMAL = 4
MANA_FAST = 5
MANA_FASTER = 6
MANA_FASTEST = 7

SPEED_SLOWEST = 240		-- Juggernaut-like things
SPEED_SLOWER = 260		-- Heavy casters or armored things
SPEED_SLOW = 270		-- Casters
SPEED_NORMAL = 290		-- Average class
SPEED_FAST = 310		-- Agile casters or dexterous classes
SPEED_FASTER = 325		-- Ninja-like speed
SPEED_FASTEST = 340		-- Sanic

HEALTH_WEAKEST = 50 -- Classes with insane mobility or other methods to avoid damage, or dumb leeroy-jenkins like classes.
HEALTH_WEAKER = 75 -- Classes with protective spells and heals or stealth classes.
HEALTH_WEAK = 90 -- An average class that was too strong at 100 health.
HEALTH_NORMAL = 100 -- Average class
HEALTH_STRONG = 110 -- An average class that was too weak at 100 health.
HEALTH_STRONGER = 125 -- Nonstealth classes with either high mobility and no healing or low mobility and some healing.
HEALTH_STRONGEST = 150 -- Tanky classes with no heals and extremely limited mobility.

--[[SPEED_SLOWEST = 270
SPEED_SLOWER = 280
SPEED_SLOW = 290
SPEED_NORMAL = 300
SPEED_FAST = 310
SPEED_FASTER = 325
SPEED_FASTEST = 340 --1500]]

TEAM_BLUE = 1
TEAM_YELLOW = 2
TEAM_GREEN = 3
TEAM_RED = 4

BLUE_NAME = "Galava"
YELLOW_NAME = "Necromancers"
GREEN_NAME = "Ix"
RED_NAME = "Dun Mir"

team.SetUp(TEAM_BLUE, BLUE_NAME, Color(0, 160, 255, 255))
team.SetUp(TEAM_YELLOW, YELLOW_NAME, Color(255, 255, 0, 255))
team.SetUp(TEAM_GREEN, GREEN_NAME, Color(0, 255, 0, 255))
team.SetUp(TEAM_RED, RED_NAME, Color(255, 0, 0, 255))

ENDGAME = false
OVERTIME = false
GAMESTART = 1

CTF_FLAG_RETURNTIME = 0

CORE_HEALTH = 5000
CORE_HEAL = 5
CORE_OVERTIME_DAMAGE = 50
CORE_HEAL_TIME = 5
CORE_MAX_MANA = 500

BONUS_WIN = 1500
BONUS_CAPTURE = 200
BONUS_RETURN = 50

END_ROUND = 0
RESPAWN_TIME = 6
RESPAWN_TIME_SUICIDE = 12

GLOBALMAXPROPS = 200
NOBUILDGLOBALMAXPROPS = 100
NOBUILD_LENGTH = 25 * 60

CRAFTER_RESPAWN = 0.5
CRAFTER_CORE_DEFENSE_BONUS = 30

BONUS_CORE_DESTROYED = 250
BONUS_CORE_DAMAGED = 15
BONUS_CORE_DEFENSE = 10

ROUND_LENGTH = 1200
VERIFY_LENGTH = 120
BUILD_LENGTH = 240
MAX_SCORE = 5
HTF_TIME = 600
KOTH_TIME = 300
TDM_KILLS = 100
TDM_SCORE = TDM_KILLS

CAPACITOR_RANGE = 768

VEHICLE_ABANDONTIME = 20
VEHICLE_INITIALTIME = 45

GC_MAX_MANA = 25000
GC_OVERTIME_MANAGAIN = GC_MAX_MANA / 100
GC_OVERTIME_MANAGAINTIME = 5
GC_HEALTH = 64000
BONUS_GC_DAMAGED = 15
GC_WARN_THRESHOLD = 500

COUNTERSPELL_CUSTOM = -1
COUNTERSPELL_DESTROY = 1
COUNTERSPELL_EXPLODE = 2

INVERSION_CUSTOM = -1
INVERSION_DESTROY = 0
INVERSION_SETOWNER = 1
INVERSION_SETOWNER_REVERSE = 2
INVERSION_SETOWNER_REVERSE_TARGET = 3
INVERSION_SETOWNER_REVERSE_TARGET_VELOCITY = 4

DMGTYPE_GENERIC = DMG_GENERIC
DMGTYPE_PHYSICAL = DMG_GENERIC
DMGTYPE_CUTTING = DMG_SLASH
DMGTYPE_IMPACT = DMG_CRUSH
DMGTYPE_PIERCING = DMG_BULLET
DMGTYPE_ARCANE = DMG_DIRECT
DMGTYPE_FIRE = DMG_BURN
DMGTYPE_SHOCK = DMG_SHOCK
DMGTYPE_COLD = DMG_DROWN
DMGTYPE_ACID = DMG_ACID
DMGTYPE_POISON = DMG_ACID
DMGTYPE_WIND = DMG_CRUSH

DAMAGETYPES = {
[DMGTYPE_GENERIC] = "Generic",
[DMGTYPE_CUTTING] = "Cutting",
[DMGTYPE_PIERCING] = "Piercing",
[DMGTYPE_IMPACT] = "Impact",
[DMGTYPE_ARCANE] = "Arcane",
[DMGTYPE_FIRE] = "Fire",
[DMGTYPE_SHOCK] = "Shock",
[DMGTYPE_COLD] = "Cold",
[DMGTYPE_POISON] = "Poison"
}
DMGTYPES = DAMAGETYPES

DMGTYPE_SLASHING = DMGTYPE_CUTTING
DMGTYPE_WIND = DMGTYPE_ENERGY
DMGTYPE_BLUDGEONING = DMGTYPE_IMPACT
DMGTYPE_BASHING = DMGTYPE_BLUDGEONING
DMGTYPE_ENERGY = DMGTYPE_SHOCK
DMGTYPE_LIGHTNING = DMGTYPE_ENERGY
DMGTYPE_ELECTRIC = DMGTYPE_LIGHTNING
DMGTYPE_ICE = DMGTYPE_COLD
DMGTYPE_WATER = DMGTYPE_COLD
DMGTYPE_AIR = DMGTYPE_ENERGY
DMGTYPE_WIND = DMGTYPE_AIR
DMGTYPE_VOID = DMGTYPE_ARCANE
DMGTYPE_BULLET = DMGTYPE_PIERCING
DMGTYPE_PIERCE = DMGTYPE_PIERCING

RESISTANCE_NORMAL = 0
RESISTANCE_CONCRETE = 1
RESISTANCE_RUBBER = 2
RESISTANCE_METAL = 3
RESISTANCE_WOOD = 4
RESISTANCE_ELECTRONIC = 5
RESISTANCE_INVULNERABLE = 6

RESISTANCE_TABLES = {}

RESISTANCE_TABLES[RESISTANCE_NORMAL] = {}
RESISTANCE_TABLES[RESISTANCE_CONCRETE] = {[DMGTYPE_GENERIC] = 1, [DMGTYPE_CUTTING] = 1, [DMGTYPE_PIERCING] = 1, [DMGTYPE_IMPACT] = 1, [DMGTYPE_ARCANE] = 1,
[DMGTYPE_FIRE] = 0.75, [DMGTYPE_ENERGY] = 0.5, [DMGTYPE_COLD] = 1.25, [DMGTYPE_POISON] = 0}

RESISTANCE_TABLES[RESISTANCE_RUBBER] = {[DMGTYPE_GENERIC] = 1, [DMGTYPE_CUTTING] = 0.75, [DMGTYPE_PIERCING] = 0.75, [DMGTYPE_IMPACT] = 0.5, [DMGTYPE_ARCANE] = 1,
[DMGTYPE_FIRE] = 1.25, [DMGTYPE_ENERGY] = 0, [DMGTYPE_COLD] = 1, [DMGTYPE_POISON] = 0}

RESISTANCE_TABLES[RESISTANCE_METAL] = {[DMGTYPE_GENERIC] = 1, [DMGTYPE_CUTTING] = 0.75, [DMGTYPE_PIERCING] = 0.75, [DMGTYPE_IMPACT] = 0.75, [DMGTYPE_ARCANE] = 1,
[DMGTYPE_FIRE] = 0.75, [DMGTYPE_ENERGY] = 1.25, [DMGTYPE_COLD] = 1, [DMGTYPE_POISON] = 0}

RESISTANCE_TABLES[RESISTANCE_WOOD] = {[DMGTYPE_GENERIC] = 1, [DMGTYPE_CUTTING] = 1, [DMGTYPE_PIERCING] = 1, [DMGTYPE_IMPACT] = 0.75, [DMGTYPE_ARCANE] = 1,
[DMGTYPE_FIRE] = 1.25, [DMGTYPE_ENERGY] = 1, [DMGTYPE_COLD] = 0.75, [DMGTYPE_POISON] = 0}

RESISTANCE_TABLES[RESISTANCE_ELECTRONIC] = {[DMGTYPE_GENERIC] = 1, [DMGTYPE_CUTTING] = 1, [DMGTYPE_PIERCING] = 1, [DMGTYPE_IMPACT] = 1, [DMGTYPE_ARCANE] = 1,
[DMGTYPE_FIRE] = 1, [DMGTYPE_ENERGY] = 1.5, [DMGTYPE_COLD] = 0.5, [DMGTYPE_POISON] = 0}

RESISTANCE_TABLES[RESISTANCE_INVULNERABLE] = {}
for k, v in pairs(DAMAGETYPES) do
	RESISTANCE_TABLES[RESISTANCE_INVULNERABLE][k] = 0
end

GM.ResistanceToString = {[RESISTANCE_CONCRETE] = "Stone", [RESISTANCE_RUBBER] = "Rubber", [RESISTANCE_METAL] = "Metal", [RESISTANCE_WOOD] = "Wood", [RESISTANCE_ELECTRONIC] = "Electronic", [RESISTANCE_INVULNERABLE] = "Invulnerable"}
GM.StringToResistance = {}
for k, v in pairs(GM.ResistanceToString) do
	GM.StringToResistance[v] = k
end

GM.ResistanceMaterials = {[RESISTANCE_CONCRETE] = "brick/brick_model", [RESISTANCE_INVULNERABLE] = "models/debug/debugwhite", [RESISTANCE_RUBBER] = "models/props_c17/FurnitureFabric003a", [RESISTANCE_METAL] = "models/props_c17/FurnitureMetal001a", [RESISTANCE_WOOD] = "models/props_wasteland/wood_fence01a"}

CLASSES[-1] =
{
	Name = "Class selection...",
	Group = "Hidden",
	Description = "",
	Speed = 1,
	Health = 100,
	Mana = 0,
	ManaRegeneration = 0,
	KillBonus = 0,
	Model = "models/player/Kleiner.mdl"
}
CLASSES[0] = CLASSES[-1]

MASK_HOVER = bit.bor(CONTENTS_OPAQUE, CONTENTS_GRATE, CONTENTS_HITBOX, CONTENTS_DEBRIS, CONTENTS_SOLID, CONTENTS_WATER, CONTENTS_SLIME, CONTENTS_WINDOW, CONTENTS_LADDER, CONTENTS_PLAYERCLIP, CONTENTS_MOVEABLE, CONTENTS_DETAIL, CONTENTS_TRANSLUCENT)
